version: '3.4'

services:

  stocks-service:
    build: 
      context: ./src
      dockerfile: ./apps/stocks-service/Faceira.Apps.Stocks.Service/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "8081:80"
      - "50001:50001"

  stocks-service-dapr:
    image: "daprio/daprd"
    network_mode: "service:stocks-service"
    depends_on:
      - stocks-service
    command: ["./daprd",
      "-app-id", "stocks-service",
      "-app-port", "80",
      "-components-path", "/resources/components",
      "-config", "/resources/configuration.yaml"
      ]
    volumes:
      - "./src/resources/dapr/:/resources"

  dapr-postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5100:5432"
    volumes:
      - dapr-postgres-volume:/var/lib/postgresql/data 
      - ./src/resources/postgres:/docker-entrypoint-initdb.d

  dapr-pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5300:80"
    volumes:
      - dapr-pg-admin-volume:/var/lib/pgadmin
      # - xpto:/pgadmin4/servers.json 
    depends_on:
      - dapr-postgres

  dapr-zipkin:
    image: openzipkin/zipkin-slim:latest
    ports:
      - "5310:9411"

volumes:
  dapr-postgres-volume:
  dapr-pg-admin-volume:
    