
alertmanager:
  enabled: false

grafana:
  enabled: true
  adminPassword: "prom-operator"
  ingress:
    enabled: false # TODO
  resources:
    limits: 
      cpu: 100m
      memory: 120Mi
    requests: 
      cpu: 100m
      memory: 120Mi

prometheusOperator:
  enabled: true
  resources: 
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi

prometheus:
  enabled: true
  ingress:
    enabled: false # TODO

kubernetesServiceMonitors: false