
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 46.6.0
    helm:
      parameters:
        - name: alertmanager.enabled
          value: "false"
        - name: grafana.enabled
          value: true
        - name: grafana.adminPassword
          value: "prom-operator"
        - name: grafana.ingress.enabled
          value: "false" # TODO
        - name: grafana.resources.limits.cpu
          value: 100m
        - name: grafana.resources.limits.memory
          value: 128Mi
        - name: grafana.resources.requests.cpu
          value: 100m
        - name: grafana.resources.requests.memory
          value: 128Mi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
    
