apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: http-binding-finnhub
spec:
  type: bindings.http
  version: v1
  metadata:
  - name: url
    value: "https://finnhub.io/api/v1/"
  - name: securityTokenHeader
    value: "X-Finnhub-Token"
  - name: securityToken
    value: "finnhub_security_token"
  - name: direction
    value: "output"